/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ef6cf400-8d2f-4cbb-8119-bfbc1ec63f38",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TXnwa7VO0",
    "aws_user_pools_web_client_id": "56mseedp26u1aj56rfo82i1ca6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://eamqcwct2venldgowv2r4t2cie.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uu5i6rt4pjhqnkzfy4pp76bs5q"
};


export default awsmobile;
